;iNES Header data
	db	"NES",$1A
	db	(PRGROM_End-PRGROM_Start)/16000	;PRG ROM
	db	(CHRROM_End-CHRROM_Start)/8000	;CHR ROM
	db	$00	;MAPPER
	db	$00	;MAPPER
	db	$00	;PRG RAM SIZE
	db	$00	;TV SYSTEM
	db	$00	;TV SYSTEM PRG RAM
	align	8	;PADDING